# fly.toml file generated for broken-wildflower-4594 on 2022-11-10T20:48:03-03:00

app = "icy-leaf-7322"
primary_region = "eze"
kill_signal = "SIGINT"
kill_timeout = 5


[mounts]
  source="mysqldata"
  destination="/data"

[env]
  MYSQL_DATABASE = "repos"
  MYSQL_USER = "web"

[processes]
  app = "--datadir /data/mysql --default-authentication-plugin mysql_native_password --performance-schema=OFF --innodb-buffer-pool-size 64M"
