# fly.toml file generated for broken-wildflower-4594 on 2022-11-10T20:48:03-03:00

app = "broken-wildflower-4594"
kill_signal = "SIGINT"
kill_timeout = 5


[mounts]
  source="mysqldata"
  destination="/data"

[env]
  MYSQL_DATABASE = "db_tasks"
  MYSQL_USER = "web"

[experimental]
  cmd = [
    "--default-authentication-plugin", 
    "mysql_native_password", 
    "--datadir", 
    "/data/mysql",
    "--performance-schema=OFF",
    "--innodb-buffer-pool-size", "64M"
  ]